### ISSUE TITLE
Update our README

### ISSUE THREAD

**Issue by mlangc** [scala-ide/scala-refactoring#130]
Our README is currently out of date and not very contributor friendly. It should mention
- that most refactoring are currently unmaintained and are waiting for contributors
- that we use SBT and not Maven
- some tips for new contributors

**Comment by fommil** [comment]
:+1: it might even be a good idea to make `scala-refactoring.org` just redirect to the github page. False information is worse than no information.

**Comment by mlangc** [comment]
I think that `scala-refactoring.org` is maintained by @misto, so we should probably involve him in the discussion...

**Comment by misto** [comment]
Just redirecting sounds good to me, I'll make the changes.

**Comment by mlangc** [comment]
All right, but I think we should keep your master thesis around somewhere.. it's very useful for understanding the library!

**Comment by fommil** [comment]
@misto can you perhaps push the current website to a `gh-pages` branch on this repo? That's the standard convention.

**Comment by misto** [comment]
That won't be so easy since it's based on Wordpress, but most of the information is outdated anyway. But we could just create a new GitHub page and upload the thesis there.

**Comment by mlangc** [comment]
I've just started working on this (unfortunately I cannot assign the issue to myself since I don't have the necessary privileges).

**Comment by mlangc** [comment]
@fommil I've just created a PR; if you happen to have some time to spare, it would be great if you could skim over this, telling me if

* if this is understandable to outsiders
* where my English could use some improvements

**Comment by misto** [comment]
Now that we have the new Readme, what about just redirecting scala-refactoring.org to this repository?

**Comment by sschaef** [comment]
I'm ok with that.

**Comment by mlangc** [comment]
This sounds like a good idea... let's close this issue as soon as this is implemented.

**Comment by sschaef** [comment]
README is updated. The only thing that is missing is that scala-refactoring.org redirects to Github

**Comment by misto** [comment]
Done!
