### ISSUE TITLE
Rename PimpedTrees

### ISSUE THREAD

**Issue by thisfred** [scala-ide/scala-refactoring#134]
Is it possible to rename 

https://github.com/scala-ide/scala-refactoring/blob/master/src/main/scala/scala/tools/refactoring/common/PimpedTrees.scala#L28

to something more descriptive and less brotastic?

**Comment by thisfred** [comment]
Perhaps `EnrichedTrees`, along the lines of this PR: https://github.com/scala/scala/pull/1931

**Comment by ieure** [comment]
+1

**Comment by sschaef** [comment]
while the change is possible it is source incompatible. @fommil Do you use the `PimpedTrees` trait in your codebase?

**Comment by fommil** [comment]
Yeah but we'd be happy to change. I've actually considered suggesting this but i thought it was in the compiler itself.

**Comment by thisfred** [comment]
Awesome, thank you for your responses. I'd be happy to cook up a PR, if that helps, and if there's a consensus about a new name.

**Comment by misto** [comment]
:+1: `EnrichedTrees` sounds good to me and is just as descriptive as pimped trees was back in 2010 when I wrote the code.

**Comment by thisfred** [comment]
cool, PR coming up.

**Comment by thisfred** [comment]
PR up here: https://github.com/scala-ide/scala-refactoring/pull/135

**Comment by sschaef** [comment]
Fixed by #135.
