### ISSUE TITLE
RFE: add import

### ISSUE THREAD

**Issue by fommil** [scala-ide/scala-refactoring#154]
in ensime we currently expect the clients to handle the adding of an import, but it would be really ace if scala-refactoring could do it in such a way that matches with (best efforts) the ordering rules.

**Comment by sschaef** [comment]
I'm not sure if I fully understand this issue. You mean that newly added imports should be added at the right location (i.e. what you get when organize imports is run) instead of at the end of the import list?

**Comment by mlangc** [comment]
I think what @fommil wants is that add imports respects the same ordering rules as organize imports. This would be a very nice feature indeed, but it is not trivial to implement. @wpopielarski what do you think?

**Comment by wpopielarski** [comment]
would be nice to consistent when organize and adding imports but I don't know exact innards.
