### ISSUE TITLE
Publish artifact for Scala 2.12.0-RC1

### ISSUE THREAD

**Issue by Sciss** [scala-ide/scala-refactoring#168]
Could you please publish the most recent stable artifact build with Scala 2.12.0-RC1 to Maven Central? Thanks!

**Comment by sschaef** [comment]
Blocked until https://github.com/scala/scala-dev/issues/219 is fixed.

**Comment by Sciss** [comment]
Yes, sorry, I noticed this after filing the issue

**Comment by sschaef** [comment]
I managed to run the tests with 2.12:
```
[error] Failed: Total 1679, Failed 51, Errors 0, Passed 1580, Skipped 48
```
Could be better ;) I guess we will have something to do here in order to make our codebase compatible with 2.12.

**Comment by SethTisue** [comment]
scala/scala-dev#219 is fixed in 2.12.0-RC2

at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/816/console I tried to compile the current code with the current 2.12, but I got some compile errors, the first of which is:

```
[scala-refactoring] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scala-refactoring-53e5d745a6d151fbe5b5f161d1aa1761b8539ce6/src/main/scala/scala/tools/refactoring/common/TreeTraverser.scala:249: not found: type ClassTypeRef
[scala-refactoring] [error]                 case typeRef: ClassTypeRef =>
[scala-refactoring] [error]                               ^
```

ClassTypeRef was removed in scala/scala@da3f7177232e7c0732d5b7d2929dbb8271d7b395

I am dropping scala-refactoring from the 2.12 community build for now.

**Comment by SethTisue** [comment]
if scala-refactoring is published for 2.12, could you add it to https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md, please?

**Comment by sschaef** [comment]
Reopen. We still didn't publish the artifacts, just fixed the build.

**Comment by SethTisue** [comment]
re-added to 2.12 community build in https://github.com/scala/community-builds/pull/407

**Comment by sschaef** [comment]
Finally, we are able to publish nightlies for 2.12.0. But now we can't update to 2.12.1 because it is not source compatible to 2.12.0...

**Comment by SethTisue** [comment]
(details on that at https://github.com/scala/scala/pull/5469#discussion_r92637723)
