### ISSUE TITLE
Publish artifact for Scala 2.12.1

### ISSUE THREAD

**Issue by Sciss** [scala-ide/scala-refactoring#178]
I'm basically re-opening #168, because there is no published artifact, yet, as far as I can see:

http://search.maven.org/#search|ga|1|scala-refactoring

**Comment by sschaef** [comment]
There are snapshots: https://oss.sonatype.org/content/repositories/snapshots/org/scala-refactoring/org.scala-refactoring.library_2.12.0/0.12.0-SNAPSHOT/

**Comment by Sciss** [comment]
ok, thanks

**Comment by wpopielarski** [comment]
well, work on 2.12.1 is hold to time when Scala IDE for 2.12.0 will be
released and this is hold until Zinc for 2.12 will be released.

2016-12-29 1:35 GMT+01:00 Hanns Holger Rutz <notifications@github.com>:

**Comment by fommil** [comment]
Hmm, we're blocked in ensime until this is available... does it require much work?

**Comment by wpopielarski** [comment]
I think we can release scala-refactoring anyway. Need to consult it with
Simon.

2017-01-06 18:06 GMT+01:00 Sam Halliday <notifications@github.com>:

**Comment by Sciss** [comment]
Just wanted to say that I'm currently not relying on this artefact any longer, so no stress with the release.
