### ISSUE TITLE
support catch-all organise import group

### ISSUE THREAD

**Issue by fommil** [scala-ide/scala-refactoring#192]
IntelliJ seems to encourage imports in this order

```
import java....

import scala...

import ... everything else...

import com.my.app...
```

which sadly cannot be met by scala-refactoring's config.

It would be good if perhaps we allowed `*` as a magic marker for this, so the user could use this config: `["java", "scala", "*", "com.my.app"]`

**Comment by fommil** [comment]
Can we please get a release?

**Comment by wpopielarski** [comment]
I believe on Monday

2017-08-24 21:49 GMT+02:00 Sam Halliday <notifications@github.com>:
