### ISSUE TITLE
Extract local from interpolated String

### ISSUE THREAD

**Issue by michih57** [scala-ide/scala-refactoring#26]
Extract local from an expression inside an interpolated string currently mangles the source code.

An example:

    val i = s"example string ${5+5}"

Extracting the expression 5+5 to the val extracted results in:

    val extracted = 5+5
    val i = extracted}"

**Comment by sschaef** [comment]
Moved to Assembla: https://www.assembla.com/spaces/scala-ide/tickets/1002571-extract-local-refactoring-doesn--39-t-work-for-expressions-in-string-interpolation#/activity/ticket:
