### ISSUE TITLE
Rename refactoring for case class parameter should also rename named arguments to apply and copy

### ISSUE THREAD

**Issue by retronym** [scala-ide/scala-refactoring#44]
![image](https://f.cloud.github.com/assets/65551/2193675/4698b0bc-9881-11e3-8897-9e71ad8142ad.png)

The competition:

![image](https://f.cloud.github.com/assets/65551/2193678/4e167662-9881-11e3-9a37-49a9cfc4b938.png)

**Comment by sschaef** [comment]
Moved to Assembla: https://www.assembla.com/spaces/scala-ide/tickets/1002572-rename-refactoring-for-case-class-parameter-should-also-rename-named-arguments-to-apply-and-copy#/activity/ticket:
