### ISSUE TITLE
Organize Imports fails when "_root_" and "scala" packages are involved

### ISSUE THREAD

**Issue by mlangc** [scala-ide/scala-refactoring#72]
See https://github.com/mlangc/scala-ide-experiments/tree/organize-imports-for-root-and-scala-72 for a minimal example.

**Comment by sschaef** [comment]
Moved to Assembla: https://www.assembla.com/spaces/scala-ide/tickets/1002573-organize-imports-fails-when--quot-_root_-quot--and--quot-scala-quot--packages-are-involved#/activity/ticket:
