### ISSUE TITLE
Replace more than N imports from same package by wildcard import

### ISSUE THREAD

**Issue by eamelink** [scala-ide/scala-refactoring#8]
I'm interested in implementing a refactoring that allows to change individual imports from a single package by a wildcard. Twitter's 'Effective Scala' for example suggests to do this when there are more than six imports from a given package.

I see the need to make exceptions for certain packages that would export too much. I think that can be handled similarly to the "always use wildcard imports when importing from these packages" feature in Scala IDE.

More problematic however is that changing imports to a wildcard might break compilation, if it causes duplicate names being imported. I think the easiest solution to that is to just not perform the operation if that happens. Is that feasible and can you from the top of your head recommend a strategy on how to this?

Work will start tomorrow evening during the first Amsterdam Scala Hackathon!

**Comment by sschaef** [comment]
Moved to Assembla: https://www.assembla.com/spaces/scala-ide/tickets/1002570#/activity/ticket:
